-- local augroup = vim.api.nvim_create_augroup
-- local autocmd = vim.api.nvim_create_autocmd
-- -- Highlight yanked text
-- local compileOnSave = augroup("compileOnSave", {})
-- autocmd("BufWritePost", {
--     callback = function()
--       vim.cmd("VimtexCompileSS")
--     end,
--     group = compileOnSave,
--     buffer = 0,
-- })
